name: iko_reliability_flutter
description: IKO Reliability Tool

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
    sdk: '>=2.16.2 <3.0.0'

dependencies:
    flutter:
        sdk: flutter
    cupertino_icons: ^1.0.2
    auto_route: ^5.0.0
    http: ^0.13.4
    flutter_html: ^3.0.0-alpha.3
    video_player_web: ^2.0.7
    wakelock_web: ^0.4.0
    html: ^0.15.0
    dropdown_search: ^5.0.1
    pluto_grid: ^5.0.0
    file_picker: ^5.0.0
    spreadsheet_decoder: ^2.0.2
    hive_flutter: ^1.1.0
    hive: ^2.2.1
    csv: ^5.0.1
    provider: ^6.0.3
    flutter_simple_treeview: ^3.0.1
    drift: ^2.3.0
    sqlite3_flutter_libs: ^0.5.0
    path_provider: ^2.0.0
    path: ^1.8.2

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^2.0.1
    auto_route_generator: ^5.0.0
    hive_generator: ^2.0.0
    drift_dev: ^2.3.3
    build_runner: ^2.2.0
    squirrel:
        git: https://github.com/RustamG/squirrel-flutter.git


flutter:
    uses-material-design: true
    fonts:
      - family: RobotoMono
        fonts:
          - asset: fonts/RobotoMono-Regular.ttf

squirrel:
  windows:
    appIcon: C:\Users\majona\GitHub\iko_reliability_flutter\iko_logo.ico
    appFriendlyName: IKO Reliability Tool
    appDescription: IKO Reliability Tool
    authors: Jonathan
    # uninstallIconPngUrl: iko_logo.png
    releaseDirectory: C:\Users\majona\Desktop\Flutter