name: Release
on:
  release:
    types:
      - created
  push:
    tags:
      - 'v*'
    branches: [ master ]

jobs:
  publish_on_win:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
    - name: building for windows
      run: flutter build windows
    - name: packaging in squirrel
      run: flutter pub run squirrel:installer_windows
    - name: get version name
      run: |
        VERSION=${GITHUB_REF_NAME#v}
        echo Version: $VERSION
        echo "VERSION=${VERSION:1}" >> $GITHUB_ENV

    - name: Release
      uses: softprops/action-gh-release@v1
      with: 
        files: |
          iko_reliability_flutter-${VERSION}-full.nupkg
          RELEASES
          Setup.exe