name: Release
on:
  release:
    types:
      - created
  push:
    tags:
      - 'v*'

jobs:
  publish_on_win:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2       
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
    - name: building for windows
      run: flutter build windows
    - name: packaging in squirrel
      run: flutter pub run squirrel:installer_windows

    - name: publish
      uses: actions/upload-artifact@v2
      with: 
        name: assets-for-download
        path: releases
